# Generated by Django 5.2.5 on 2026-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_regularuserproxy_superuserproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_external',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
