# Generated by Django 5.2.5 on 2026-07-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar_external'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar_external',
            new_name='avatar_url',
        ),
    ]
