# Generated by Django 5.2.5 on 2026-09-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_avatar_external_customuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
    ]
