# Generated by Django 5.2.5 on 2026-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar Google'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
